### PR TITLE
WP 5.5 auto-update UI support for externally managed plugins

### LINKED ISSUE #1: Ensure WordPress Core plugin and theme auto-update UIs are properly supported
**Summarize the issue (briefly)**
WordPress 5.5 will introduce a native UI for managing plugin and theme auto-updates on a per plugin/theme basis. For plugins _not_ hosted on the .org directory, there are a few requirements that have been [documented in a recent developer note](https://make.wordpress.org/core/2020/07/30/recommended-usage-of-the-updates-api-to-support-the-auto-updates-ui-for-plugins-and-themes-in-wordpress-5-5/).

The main take away from that post is the `no_update` property is a requirement for the auto-update UI to work correctly for externally hosted plugins.

When an update is not available for a plugin, it must be added to the `no_update` list within the transient. This is the only way for WordPress to know that an externally hosted plugin is in fact checking for updates when there currently are none to apply, so this controls whether the auto-update toggle is displayed.

**Steps to reproduce**
  1. Install WP 5.5 (currently in RC2) using the beta tester plugin and install either the Mojo or Bluehost plugins.
  2. Head to the Plugins page
  3. Notice there is no link for managing the auto-update status for the plugin.

### PR DESCRIPTION
**Pull request by desrosj**
Fixes #1.

### CODE REVIEW

**Comment by wpscholar** [comment]
@desrosj I ended up changing your implementation to go with [this](https://github.com/bluehost/endurance-wp-plugin-updater/pull/2/files#diff-ff6086bc29715fa23f36887454dd08a2R75). Reason being, that `$container['plugin']` is actually an instance of the [`Endurance_WP_Plugin_Updater/Plugin`](https://github.com/bluehost/endurance-wp-plugin-updater/blob/master/Plugin.php#L3) class and doesn't output the necessary data as per the example in the [dev note](https://make.wordpress.org/core/2020/07/30/recommended-usage-of-the-updates-api-to-support-the-auto-updates-ui-for-plugins-and-themes-in-wordpress-5-5/). 

I also added linting checks and updated the code to pass while I was at it.

**Review by 0aveRyan — APPROVED** [review]

**Comment by 0aveRyan** [comment]
This lgtm at this point

File: Updater.php [hunk 1]
```diff
@@ -11,74 +11,112 @@
...
+						'id'            => $plugin->basename(),
+						'slug'          => $plugin->slug(),
+						'plugin'        => $plugin->basename(),
+						'new_version'   => $plugin->version(),
+						'url'           => $plugin->uri(),
+						'package'       => '',
+						'icons'         => array(),
+						'banners'       => array(),
+						'banners_rtl'   => array(),
+						'tested'        => $plugin->requires_wp_version(),
```
Comment (desrosj) [inline Updater.php]: Just checking that this is the right value. Tested up to and the minimum version requirement seem like they would be different. I don't know that this will be displayed anywhere, but could result in saying the plugin has not been tested against recent versions.

**Review by desrosj — COMMENTED** [review]
Looks good. We should add the requires WP value to the plugin, but it's not essential for this update (I don't believe that is enforced or has any impact for `no_updates`, only for an update being offered, and there is a value passed that can be used in `version_compare()`.

(Can't approve my own PR, but 👍🏼)
